---
- name: Create user repos dir
  file: path={{openstack_dev_repos_dir}} state=directory
        mode=0755
        owner={{ansible_env.USER}}
  become: true
- name: Create openstack repos dir
  file: path={{openstack_dev_repos_dir}}/openstack state=directory
- name: Check out oslo.tools
  git: repo=git://git.openstack.org/openstack/oslo.tools
       dest={{openstack_dev_repos_dir}}/openstack/oslo.tools
       update=no
       accept_hostkey=yes
- name: Install update.sh
  copy: src=update.sh
        dest={{openstack_dev_repos_dir}}/update.sh
        mode=0755
        force=yes
- name: Check out requirements for wheel building tools
  git: repo=git://git.openstack.org/openstack/requirements
       dest={{openstack_dev_repos_dir}}/openstack/requirements
       update=no
       accept_hostkey=yes
- name: Set up cron
  cron: name="refresh cache"
        hour=1
        user={{ansible_env.USER}}
        job="cd {{openstack_dev_repos_dir}}; ./update.sh"
  become: true