---
- name: Install pastebinit
  apt: name=pastebinit state=latest
  become: true
- name: Install ~/.pastebinit.xml
  copy: src=pastebinit.xml
        dest={{ansible_env.HOME}}/.pastebinit.xml
        mode=0644
        owner={{ansible_env.USER}}
- name: Install git restack
  pip: name=git-restack
  become: true
- name: Install LaTeX
  apt:
    name: "{{item}}"
  with:
    - texlive-xetex
    - latexmk
  become: true
